modLoader = "javafml"
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "CC0-1.0"
issueTrackerURL=""
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId = "protoweaver"
version = "0.debug-build"
displayName = "ProtoWeaver"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL=""
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="untitled1.png" #optional
authors="MrNavaStar"
description = ''

# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
displayTest="IGNORE_ALL_VERSION"
